//
//  PSCData.swift
//  GovLedger
//


import Foundation

struct PSCData {
    // This static dictionary maps all top-level PSC codes (both services and products)
    // to their official descriptions, sourced from the "psc_depth_1_codes.json" file.
    static let categories: [String: String] = [
        "10": "WEAPONS",
        "11": "NUCLEAR ORDNANCE",
        "12": "FIRE CONTROL EQPT.",
        "13": "AMMUNITION AND EXPLOSIVES",
        "14": "GUIDED MISSLES",
        "15": "AEROSPACE CRAFT AND STRUCTURAL COMPONENTS",
        "16": "AEROSPACE CRAFT COMPONENTS AND ACCESSORIES",
        "17": "AEROSPACE CRAFT LAUNCHING, LANDING, GROUND HANDLING AND SERVICING EQUIPMENT",
        "18": "SPACE VEHICLES",
        "19": "SHIPS, SMALL CRAFT, PONTOON, DOCKS",
        "20": "SHIP AND MARINE EQUIPMENT",
        "22": "RAILWAY EQUIPMENT",
        "23": "MOTOR VEHICLES, CYCLES, TRAILERS",
        "24": "TRACTORS",
        "25": "VEHICULAR EQUIPMENT COMPONENTS",
        "26": "TIRES AND TUBES",
        "28": "ENGINES AND TURBINES AND COMPONENT",
        "29": "ENGINE ACCESSORIES",
        "30": "MECHANICAL POWER TRANSMISSION EQPT",
        "31": "BEARINGS",
        "32": "WOODWORKING MACHINERY AND EQPT",
        "34": "METALWORKING MACHINERY",
        "35": "SERVICE AND TRADE EQPT",
        "36": "SPECIAL INDUSTRY MACHINERY",
        "37": "AGRICULTURAL MACHINERY AND EQPT",
        "38": "CONSTRUCT/MINE/EXCAVATE/HIGHWY EQPT",
        "39": "MATERIALS HANDLING EQPT",
        "40": "ROPE, CABLE, CHAIN, FITTINGS",
        "41": "REFRIG, AIR CONDIT/CIRCULAT EQPT",
        "42": "FIRE/RESCUE/SAFETY; ENVIRO PROTECT",
        "43": "PUMPS AND COMPRESSORS",
        "44": "FURNACE/STEAM/DRYING; NUCL REACTOR",
        "45": "PLUMBING, HEATING, WASTE DISPOSAL",
        "46": "WATER PURIFICATION/SEWAGE TREATMENT",
        "47": "PIPE, TUBING, HOSE, AND FITTINGS",
        "48": "VALVES",
        "49": "MAINT/REPAIR SHOP EQPT",
        "51": "HAND TOOLS",
        "52": "MEASURING TOOLS",
        "53": "HARDWARE AND ABRASIVES",
        "54": "PREFAB STRUCTURES/SCAFFOLDING",
        "55": "LUMBER, MILLWORK, PLYWOOD, VENEER",
        "56": "CONSTRUCTION AND BUILDING MATERIAL",
        "58": "COMM/DETECT/COHERENT RADIATION",
        "59": "ELECTRICAL/ELECTRONIC EQPT COMPNTS",
        "60": "FIBER OPTIC",
        "61": "ELECTRIC WIRE, POWER DISTRIB EQPT",
        "62": "LIGHTING FIXTURES, LAMPS",
        "63": "ALARM, SIGNAL, SECURITY DETECTION",
        "65": "MEDICAL/DENTAL/VETERINARY EQPT/SUPP",
        "66": "INSTRUMENTS AND LABORATORY EQPT",
        "67": "PHOTOGRAPHIC EQPT",
        "68": "CHEMICALS AND CHEMICAL PRODUCTS",
        "69": "TRAINING AIDS AND DEVICES",
        "70": "INFORMATION TECHNOLOGY EQUIPMENT (INCLD FIRMWARE) SOFTWARE,SUPPLIES& SUPPORT EQUIPMENT",
        "71": "FURNITURE",
        "72": "HOUSEHOLD/COMMERC FURNISH/APPLIANCE",
        "73": "FOOD PREPARATION/SERVING EQPT",
        "74": "OFFICE MACH/TEXT PROCESS/VISIB REC",
        "75": "OFFICE SUPPLIES AND DEVICES",
        "76": "BOOKS, MAPS, OTHER PUBLICATIONS",
        "77": "MUSICAL INST/PHONOGRAPH/HOME RADIO",
        "78": "RECREATIONAL/ATHLETIC EQPT",
        "79": "CLEANING EQPT AND SUPPLIES",
        "80": "BRUSHES, PAINTS, SEALERS, ADHESIVES",
        "81": "CONTAINERS/PACKAGING/PACKING SUPPL",
        "83": "TEXTILE/LEATHER/FUR; TENT; FLAG",
        "84": "CLOTHING, INDIVIDUAL EQUIPMENT, INSIGNA, AND JEWELRY",
        "85": "TOILETRIES",
        "87": "AGRICULTURAL SUPPLIES",
        "88": "LIVE ANIMALS",
        "89": "SUBSISTENCE",
        "91": "FUELS, LUBRICANTS, OILS, WAXES",
        "93": "NONMETALLIC FABRICATED MATERIALS",
        "94": "NONMETALLIC CRUDE MATERIALS",
        "95": "METAL BARS, SHEETS, SHAPES",
        "96": "ORES, MINERALS AND PRIMARY PRODUCTS",
        "99": "MISCELLANEOUS",
        "AA": "AGRICULTURE R&D SERVICES",
        "AB": "Community and Regional Development R&D Services",
        "AC": "C – National Defense R&D Services",
        "AD": "DEFENSE (OTHER) R&D",
        "AE": "ECONOMIC GROWTH/PRODUCTIVITY R&D",
        "AF": "Education, Training, Employment, and Social Services R&D Services",
        "AG": "Energy R&D Services",
        "AH": "Natural Resources and Environment R&D Services",
        "AJ": "General Science and Technology R&D Services",
        "AK": "Commerce and Housing Credit R&D Services",
        "AL": "Income Security R&D Services",
        "AM": "International Affairs R&D Services",
        "AN": "N – Health R&D Services",
        "AP": "NATURAL RESOURCES R&D",
        "AQ": "SOCIAL SERVICES R&D",
        "AR": "Space R&D Services",
        "AS": "Transportation R&D Services",
        "AT": "TRANSPORTATION (OTHER) R&D",
        "AU": "TRANSPORTATION (OBSOLETE GROUP)",
        "AV": "MINING R&D",
        "AZ": "OTHER RESEARCH/DEVELOPMENT",
        "B": "SPECIAL STUDIES/ANALYSIS, NOT R&D",
        "C": "ARCHITECT/ENGINEER SERVICES",
        "D": "IT AND TELECOM - INFORMATION TECHNOLOGY AND TELECOMMUNICATIONS",
        "E": "PURCHASE OF STRUCTURES/FACILITIES",
        "F": "NATURAL RESOURCES MANAGEMENT",
        "G": "SOCIAL SERVICES",
        "H": "QUALITY CONTROL, TEST, INSPECTION",
        "J": "MAINT, REPAIR, REBUILD EQUIPMENT",
        "K": "MODIFICATION OF EQUIPMENT",
        "L": "TECHNICAL REPRESENTATIVE SVCS.",
        "M": "OPERATION OF GOVT OWNED FACILITY",
        "N": "INSTALLATION OF EQUIPMENT",
        "P": "SALVAGE SERVICES",
        "Q": "MEDICAL SERVICES",
        "R": "SUPPORT SVCS (PROF, ADMIN, MGMT)",
        "S": "UTILITIES AND HOUSEKEEPING",
        "T": "PHOTO, MAP, PRINT, PUBLICATION",
        "U": "EDUCATION AND TRAINING",
        "V": "TRANSPORT, TRAVEL, RELOCATION",
        "W": "LEASE/RENT EQUIPMENT",
        "X": "LEASE/RENT FACILITIES",
        "Y": "CONSTRUCT OF STRUCTURES/FACILITIES",
        "Z": "MAINT, REPAIR, ALTER REAL PROPERTY"
    ]
}
